### PR TITLE
Add new token spec for size scale

### PR DESCRIPTION
**Pull request by blackfalcon**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #71 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

This feature release will add a new scale for size tokens using a `X00` value scale. This update also
deprecates the current scale of XL named values.

Screen Shot 2022-09-23 at 10 42 46 AM

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by jordanjones243 — APPROVED** [review]

**Comment by leeejune** [comment]
@blackfalcon are we adding all of those tokens or just changing the naming convention? Previously we did not have sizes 900 (4.5rem), 700 (3.5rem), 500 (2.5rem).

**Comment by blackfalcon** [comment]
Updated to include proper deprecations documentation. 

Screen Shot 2022-09-26 at 1 47 48 PM

**Comment by blackfalcon** [comment]
> @blackfalcon are we adding all of those tokens or just changing the naming convention? Previously we did not have sizes 900 (4.5rem), 700 (3.5rem), 500 (2.5rem).

Both. Using the opportunity to fix the size ladder and add the new values in the same PR.

**Comment by leeejune** [comment]
@blackfalcon Do we want to add all of those options? I added sizes 600 and 1000 because there was a need for it, but I'm not sure if we have reasons to add all of the other in between sizes (sizes 500, 700, 900).

**Comment by blackfalcon** [comment]
> @blackfalcon Do we want to add all of those options? I added sizes 600 and 1000 because there was a need for it, but I'm not sure if we have reasons to add all of the others in between sizes (sizes 500, 700, 900).

I added in the 500, 700 and 900 as there are areas where that value is hard-coded into the UIs or there are some other random uses. 

Is there a harm in adding them or is there something else we need to do?

**Comment by leeejune** [comment]
@blackfalcon Got it. No harm, but just concerned with having every spacing option for the designers in Figma. What do you think about keeping those in code only? I might need to think more about the implications of giving every single spacing option to designers.

**Comment by blackfalcon** [comment]
> What do you think about keeping those in code only? I might need to think more about the implications of giving every single spacing option to designers.

That's your call.

**Review by leeejune — APPROVED** [review]

**Pull request merged**
